open-api updated
natiq-foundation/natiq-api-rust pull request #104
Opened 2023-08-30 20:27 UTC by ahadvl

Add some new routers to open-api file.

2023-08-30 20:31 UTC, Al-Abd approved these changes
@AzerothA important review.

2023-08-31 10:49 UTC, AzerothA requested changes
Congratulations @ahadvl for you first pull request to Natiq-API, you did a pretty good job at fixing and updating the open-api file however there is some changes I was considering and I wrote comments for you to check, and please start the first word uppercase in every sentence, and don't overuse the 's for example in user, using the 's depends on the context of sentence.

2023-08-31 10:49 UTC, AzerothA commented on open-api.json
> +                "description": "Add the new organization",
No need for 'Add' keyword, please remove it. Or reply with the reasoning behind used grammar.

2023-08-31 10:49 UTC, AzerothA commented on open-api.json
> +                        "description": "This means new organization was created"
Please use this term in every response description, or change the grammar to look a like the past descriptions.

2023-08-31 10:49 UTC, AzerothA commented on open-api.json
> +                                        "description": "The action that the user need to implement on controller",
This sentence makes reader confused. Please alternate it with more simple and understandable sentence.

2023-08-31 10:49 UTC, AzerothA commented on open-api.json
> +                                        "description" : "each condition must include name & value, Possible Conditions: isOwner(Boolean)",
You kinda changed the concept of description in this part, before this section used to describe object attribute, but in this case you described the policy of using conditions, please reply with comment if you have an explanation.

2023-08-31 10:49 UTC, AzerothA commented on open-api.json
> +                                        "example": "[{ \"name\": \"isOwner\", \"value\":\"True\"]"
The value of 'value' attribute must not start with uppercase latter.

2023-08-31 10:49 UTC, AzerothA commented on open-api.json
> +                "description": "Delet permission with id you specified",
Typo: delet -> delete

2023-08-31 10:49 UTC, AzerothA commented on open-api.json
> +            "description": "Return the new user's token",
The 's is overused in user word.

2023-08-31 14:11 UTC, AzerothA requested changes
Please, read comments properly, or give you thoughts about comments as a reply. And there's some new typo.

2023-08-31 14:11 UTC, AzerothA commented on open-api.json
> +                                        "description" : "Array of conditions, each condition is an object includ has name & value, currently only possible condition is isOwner(Boolian)",
Typo Boolean

2023-08-31 14:11 UTC, AzerothA commented on open-api.json
> +                                        "description" : "Array of conditions, each condition is an object includ has name & value, currently only possible condition is isOwner(Boolian)",
Typo Boolean

2023-08-31 14:11 UTC, nyzd commented on open-api.json
> +                                        "description": "The action that the user need to implement on controller",
The implement word doesn't suit in this sentence.

2023-08-31 14:11 UTC, AzerothA commented on open-api.json
> +                        "description": "User full profile was edited"
'was' Word is not grammatically correct in this sentence. Please remove it.

2023-08-31 15:09 UTC, nyzd approved these changes
Fair enough.

2023-08-31 18:31 UTC, merged