Fix Bug and update routers
natiq-foundation/natiq-api-rust pull request #202
Opened 2024-11-24 08:34 UTC by Silence0ne

Add the required section to the router's properties
In the phrase section,  router delete was added 
fix some bugs

2024-11-24 14:29 UTC, Silence0ne reviewed
There is no problem @al-abd

2024-11-24 15:21 UTC, al-abd approved these changes

2024-11-24 16:57 UTC, al-abd approved these changes

2024-11-24 17:36 UTC, nyzd requested changes
There is some typo in router or response descriptions, also some is not correct.

2024-11-24 17:36 UTC, nyzd commented on open-api.json
> +                  "bismillah": {
Currently, the translation edit router doesn't support bismillah field.

2024-11-24 17:36 UTC, nyzd commented on open-api.json
> +        "description": "Edit phrase whit id you specified",
This router doesn't edit phrases with id or uuid, instead, it requires language code e.g. `en` in the path, then modifies phrases belonging to that language code.

2024-11-24 17:36 UTC, nyzd commented on open-api.json
> +      "post": {
This router also requires a body as JSON (declared as `web::Json<HashMap<String, Option<String>>>` in source code) i.e.
```json
{
    "<PHRASE>": "<TRANSLATION>"
}
```
This will Edit or create phrases if doesn't exist.

2024-11-24 17:36 UTC, nyzd commented on open-api.json
> +      "delete": {
Doesn't delete a phrase it removes every phrase that is related to the language code.

2024-11-24 17:36 UTC, nyzd commented on open-api.json
>              "description": "Return the phrase with id you specified"
Return's **list** of phrases related to `language`

2024-11-28 13:35 UTC, nyzd approved these changes

2024-11-28 13:40 UTC, al-abd approved these changes

2024-11-28 13:41 UTC, merged